### ISSUE TITLE
Getting sequencing depth correspond to .vcf file

### ISSUE THREAD

**Issue by beginner984** [brentp/mosdepth#78] opened 2019-04-04 16:12 UTC
Hi,
I have called SNV for tumour and matched normal samples, now I have .vcf and I want to get tumour and normal sequencing depth something like below

```
> head(mut_data[,c(1,3:9)])
    Sample CHROM       POS REF ALT Tumor_Varcount Tumor_Depth Normal_Depth
1 CHC2432T  chr1 102961055   G   A              4          64           62
2 CHC2432T  chr1 105492588   A   T              7          66           73
3 CHC2432T  chr1 108628724   C   T              4          45           54
4 CHC2432T  chr1 109692113   G   T              2          53           29
5 CHC2432T  chr1 109692114   G   T              2          53           31
6 CHC2432T  chr1 120676701   T   C              3          48           87
> 
```

By mosdepth I was able to get depth in bed format but the positions are not the same with .vcf file while my goal is to add sequencing depth for tumour and normal to this table. Could you please help to get how I could extract sequencing depth of position correspond to .vcf file?

Any help please?

**Comment by ATpoint** [comment] 2019-04-04 16:50
Cross-posted on [BioStars](https://www.biostars.org/p/373131)

**Comment by RamRS** [comment] 2019-04-04 18:10
I don't think this belongs as a GitHub issue. It's a question on how to use the tool and not a bug or feature request as such.

**Comment by brentp** [comment] 2019-08-24 03:06
this is indeed out of scope for mosdepth. you can use the output to annotate your file.

**Closed by brentp** 2019-08-24 03:06 UTC
