### ISSUE TITLE
unhandled exception: pair_depth == 0

### ISSUE THREAD

**Issue by chapmanb** [brentp/mosdepth#6] opened 2017-09-01 15:44 UTC
Brent;
Thanks again for helping get mosdepth packaged and ready to go. I've done some initial integration work in bcbio and started testing on larger inputs and ran into an assertion error rated to pair_depth:
```
mosdepth -t 2 -F 1804 -b /mnt/work/NA12878-hg38-val/work/bedprep/cov-cov-cov-Exome-AZ.bed -d /mnt/work/NA12878-hg38-val/work/bcbiotx/tmpxFqJGS/cov-cov-cov-Exome-AZ-distribution.txt /mnt/work/NA12878-hg38-val/work/align/NA12878-1/NA12878-1-sort.bam > /mnt/work/NA12878-hg38-val/work/bcbiotx/tmpRCOY_q/cov-cov-cov-Exome-AZ-coverage.bed
Traceback (most recent call last)
mosdepth.nim(435)        mosdepth
mosdepth.nim(240)        window_main
system.nim(3554)         failedAssertImpl
system.nim(3546)         raiseAssert
system.nim(2656)         sysFatal
Error: unhandled exception: pair_depth == 0  [AssertionError]
```
This is publicly available data so I can try to isolate to a test case but it's a big whole genome run so am not sure about the best way to narrow it down on a first glance. If just the traceback is not useful I'll look into slicing and dicing the BED to try and provide a reproducible case. Thanks again.

**Comment by brentp** [comment] 2017-09-01 16:12
thanks for reporting. looks like mosdepth got built in debug mode which is good for ... debugging .. but will slow it down dramatically. 

For this case, if you can edit and compile nim on your cluster quickly, you could change line 240 to read:

```
            assert pair_depth == 0, $rec.qname & ":" & $rec & " " & $mate.qname & ":" & $mate
```

then it will give us the read name so you could extract that into a bam and I could debug. I'll also look into this on my end but haven't seen it yet.

**Comment by brentp** [comment] 2017-09-01 16:19
can you share that bed file? I have an NA12878 bam that I can use.

**Comment by brentp** [comment] 2017-09-01 19:28
I have a reproducer. I'll fix and let you know.

**Comment by brentp** [comment] 2017-09-01 19:58
This was an easy fix. It only occurs on the MT chromosome where we have coverage at position 0. I was assuming 0 was a good sentinel.

I'll push a fix for this shortly. I also made it show a warning message when it's built in debug mode at that will be > 2 times slower than when built in release mode.

**Closed** 2017-09-01 20:11 UTC

**Comment by brentp** [comment] 2017-09-01 20:14
Note the change to the travis.yml in this changeset: https://github.com/brentp/mosdepth/commit/b71e37734166e5bfd0ffffa8c215a38caec821cd#diff-354f30a63fb0907d4ad57269548329e3R12

that will cause it to build in release mode.

**Comment by brentp** [comment] 2017-09-01 20:16
in this change. rather: https://github.com/brentp/mosdepth/commit/27d20aeed93eb88dc3b2265d0bb89b67e0a9993b

**Comment by chapmanb** [comment] 2017-09-02 11:51
Brent -- thanks so much for the debugging, quick fix, and catching the build issues. I rebuilt the latest version of the bioconda package as a release and tested and all is working great on my test case. Thank you again for all the help getting this running.
