### ISSUE TITLE
lower coverage observed than actual 

### ISSUE THREAD

**Issue by kkapuria3** [brentp/mosdepth#42] opened 2018-05-24 19:29 UTC
I was trying to run mosdepth on few large *bam* files (40 GB) generated from human data. I ran mosdepth without `-n` option and calculated the *average autosomal coverage*, it was way lower than what it was previously calculated by some other tool.  To confirm, I loaded the bed file in IGV and found that mosdepth actually reports *2* less coverage at some spots than its actually observed. I am wondering what is setting this *coverage calculation* off

**Comment by brentp** [comment] 2018-05-24 20:09
`mosdepth` does not double-count overlapping paired-end reads so if you have
```
R1: -------->
R2:     <--------------
```
it will not count the center overlap as depth 2. it will be depth 1. this might be the cause of the difference you are observing, but I can't know without access to (that part of) the bam. I have evaulated the coverage accuracy of mosdepth in many ways and had many users with similar questions to yours and have never found a problem with the reported coverage.

**Comment by brentp** [comment] 2018-06-08 03:01
Closing. If you can provide data to reproduce, please share

**Closed by brentp** 2018-06-08 03:01 UTC

**Comment by kkapuria3** [comment] 2018-06-08 17:41
Sure. I will update you.
